apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  ports:
    - port: 8080
      name: primary
      targetPort: 8080
    - port: 50000
      name: agent
      targetPort: 50000
  selector:
    app: jenkins
  type: ClusterIP
